Repository OxfordIHTM/rstats-exercises, pull requests merged in 2024-02, with the labels that each got.

#26 Clifford
  exercise1.R
  rstats-exercises.R
Labels: analysis, data

#4 Mariano
  exercise1.R
Labels: analysis, data

#31 add dependency to covidphtext
  .github/workflows/check-workflow.yml
Labels: bug, infrastructure, testing

#36 create individual exercise check workflow
  .github/workflows/check-exercise-1.yml
  .github/workflows/check-exercise-2.yml
  .github/workflows/check-exercise-3.yml
  .github/workflows/check-exercise-4.yml
  .gitignore
Labels: enhancement, infrastructure, reporting

#37 update Rmds
  .github/workflows/check-workflow.yml
  .gitignore
  exercise1.Rmd
  exercise2.Rmd
  exercise3.Rmd
  exercise4.Rmd
Labels: documentation, reporting

#27 exercise 3, part 1 and 2
  exercise3.R
Labels: analysis, data

#43 refactor and tidy up exercise1.R script so far
  exercise1.R
Labels: analysis, data, refactor

#38 plot rain over time
  exercise3.R
Labels: analysis, data

#44 refactor and tidy up exercise3
  exercise3.R
Labels: refactor

#45 refactor and tidy up scripts from contributors' branches
  exercise1.R
  exercise3.R
Labels: refactor

#46 update gha workflows
  .github/workflows/check-exercise-4.yml
  .github/workflows/check-workflow.yml
Labels: bug

#29 Exercise 4: Text mining
  README.Rmd
  exercise1.Rmd
  exercise4.Rmd
  exercise4.md
  exercise4_files/figure-gfm/unnamed-chunk-1-1.png
Labels: analysis, data, reporting
